# Makefile configuration for RevyScript
# 
# Author: munter@diku.dk
#
# This file should be copied and adapted to your local environment


# Revuename. Be sure to combine name and year for better autogenerated views
revuename := Biorevy 2010

# Get revue working directory, ignore symlinks
revuedir := $(shell cd .. && pwd -P)

# Define where the scripts are placed.
scriptdir := $(revuedir)/adm/scripts

# Where to put the datafile
json := $(revuedir)/json.js

# The directories where original .tex materials will be placed
sketchdir := $(revuedir)/sketches
songdir := $(revuedir)/sange
bitsdir := $(revuedir)/brokker

# The acts plan. A cleartext file with act headings and material order
plan := $(revuedir)/adm/aktoversigt.plan

# Auto generated PDF output placements
manus := $(revuedir)/Manuskript.pdf
acts := $(revuedir)/Aktoversigt.pdf
roles := $(revuedir)/Rolleoversigt.pdf
signup := $(revuedir)/Rolletilmelding.pdf
props := $(revuedir)/Rekvisitliste.pdf

